name: Build and Deploy Jekyll Site 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby and Build Jekyll 
      uses: helaili/jekyll-action@2.0.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: 'gh-pages'

    - name: Deploy to GitHub Pages
      users: peaceiris/actions-gh-pages@v3
      with: 
        github_token: ${{  secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages

  